config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:index, :show, :destroy]
  resources :cars
end

app/models/place_rent.rb
class PlaceRent < ApplicationRecord
  belongs_to :car, optional: true
  belongs_to :parking, optional: true
  accepts_nested_attributes_for :car
  accepts_nested_attributes_for :parking

  validates :starts_at, :ends_at, :parking, :car, presence: true

  def calculate_price
    hours1 = (ends_at - starts_at)/3600
    if hours1 % 24 == 0
       left_hours = 0
    else
      left_hours = hours1 % 24
    end
    days  = (hours1 - left_hours)/24
    hours = left_hours.ceil

    day_price = parking.day_price
    hour_price = parking.hour_price

    price = day_price * days + hour_price * hours
  end

  class CreatePlaceRentsCallbacks
    def self.after_create(place_rent)
      place_rent.price = place_rent.calculate_price
      place_rent.save
    end
  end

  after_create CreatePlaceRentsCallbacks
end

app/controllers/place_rents_controller.rb
class PlaceRentsController < ApplicationController
  before_action :authenticate_account!

  def index
    @place_rents = PlaceRent.all
  end

  def show
    @place_rent = PlaceRent.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:error] = "There is no such route"
    redirect_to action: "index"
  end

  def new
    @place_rent = PlaceRent.new
    @place_rent.build_car
    @place_rent.build_parking
    @parking_id = params[:parking_id]
  end

  def create
    @place_rent = PlaceRent.new(place_rent_params)

    if @place_rent.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def destroy
    @place_rent = PlaceRent.find(params[:id])
    @place_rent.destroy

    redirect_to place_rents_path
  end

  private
  def place_rent_params
    params.require(:place_rent).permit(:starts_at, :ends_at, :car_id, :parking_id)
  end
end

app/views/place_rents/_form.html.erb
<%= form_for @place_rent, url: parking_place_rents_path(@parking_id), local: true do |form| %>

  <% if @place_rent.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@place_rent.errors.count, "error") %> prohibited
        this place_rent from being saved:
      </h2>
      <ul>
        <% @place_rent.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.collection_select(:car_id, Car.all, :id, :model) %><br>
  <%= form.collection_select(:parking_id, Parking.all, :id, :id) %>

  <p>
    <%= form.label :starts_at %><br>
    <%= form.text_field :starts_at %>
  </p>

  <p>
    <%= form.label :ends_at %><br>
    <%= form.text_area :ends_at %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', parkings_path %>

app/views/place_rents/index.html.erb
<h1>List of all place rents</h1>
<table style="width:100%; text-align: center;">
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Hour price</th>
    <th>Day price</th>
    <th>Total price</th>
  </tr>
  <% @place_rents.each do |place_rent| %>
    <tr>
      <td><%= place_rent.starts_at %></td>
      <td><%= place_rent.ends_at %></td>
      <td><%= place_rent.parking&.hour_price %></td>
      <td><%= place_rent.parking&.day_price %></td>
      <td><%= place_rent.price %></td>
      <td><%= link_to "Details", place_rent_path(place_rent.id) %></td>
      <td><%= link_to "Delete", place_rent_path(place_rent), method: :delete, data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
</table>
<ul>
  <li><%= link_to "List of cars", cars_path %></li>
  <li><%= link_to "List of parkings", parkings_path %></li>
</ul>

app/views/place_rents/new.html.erb
<h1>New place rent</h1>

<%= render "place_rents/form" %>

app/views/place_rents/show.html.erb
<h3>Details to place rent</h3>
<pre>
Parking address: <%= @place_rent.parking&.address&.city %>, <%= @place_rent.parking&.address&.street %>
Parking hour price: <%= @place_rent.parking&.hour_price %>
Parking day price: <%= @place_rent.parking&.day_price %>
Car model: <%= @place_rent.car&.model %>
Start date: <%= @place_rent.starts_at %>
End date: <%= @place_rent.ends_at %>
Action: <%= link_to "Back to list", place_rents_path %>
</pre>