config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:index, :show, :destroy]
  resources :cars
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :owner, class_name: 'Person', optional: true
  belongs_to :address, optional: true
  has_many :place_rents
  has_one :account
  accepts_nested_attributes_for :address

  validates :hour_price, :day_price, :places, numericality: true, presence: true
  enum kind: [:outdoor, :indoor, :private, :street], _prefix: :parking

  scope :min_hour_price, ->(min_hour_price) { where('hour_price >= :min_hour_price', { min_hour_price: min_hour_price }) }
  scope :max_hour_price, ->(max_hour_price) { where('hour_price <= :max_hour_price', { max_hour_price: max_hour_price }) }

  scope :min_day_price, ->(min_day_price) { where('day_price >= :min_day_price', { min_day_price: min_day_price }) }
  scope :max_day_price, ->(max_day_price) { where('day_price <= :max_day_price', { max_day_price: max_day_price }) }

  scope :public_kinds, -> { where(kind: [:outdoor, :indoor, :street]) }

  class ParkingCallbacks
    def after_destroy(parking)
      parking.place_rents.each do |place_rent|
        place_rent.ends_at = Time.now
        place_rent.save
      end
    end
  end

  after_destroy ParkingCallbacks.new

  def self.search(search_criteria)
    if search_criteria == nil || search_criteria.empty?
      Parking.all
    else
      parkings = Parking.all

      city = search_criteria[:search]
      parkings = Parking.left_joins(:address).merge(Address.city(city)) if city.present?

      min_hour_price = search_criteria[:min_hour_price]
      parkings = parkings.min_hour_price(min_hour_price) if min_hour_price.present?

      max_hour_price = search_criteria[:max_hour_price]
      parkings = parkings.max_hour_price(max_hour_price) if max_hour_price.present?

      min_day_price = search_criteria[:min_day_price]
      parkings = parkings.min_day_price(min_day_price) if min_day_price.present?

      max_day_price = search_criteria[:max_day_price]
      parkings = parkings.max_day_price(max_day_price) if max_day_price.present?

      private_parking = search_criteria[:private]

      public_parking = search_criteria[:public]

      if public_parking.present? && private_parking.present?
        parkings
      elsif public_parking.present?
        parkings = parkings.public_kinds if public_parking.present?
      elsif private_parking.present?
        parkings = parkings.parking_private if private_parking.present?
      else
        parkings = []
      end

      parkings
    end
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :authenticate_account!, except: [:index]

  def index
    @parkings = Parking.search(search_params)
  end

  def show
    @parking = Parking.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:error] = "There is no such route"
    redirect_to action: "index"
  end

  def new
    @parking = Parking.new
    @parking.build_address
  end

  def edit
    @parking = Parking.includes(:address).find(params[:id])
  end

  def create
    @parking = Parking.new(parking_params)
    @parking.owner_id = current_person.id

    if @parking.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def update
    @parking = Parking.find(params[:id])

    if @parking.update(parking_params)
      redirect_to @parking
    else
      render 'edit'
    end
  end

  def destroy
    @parking = Parking.find(params[:id])
    @parking.destroy

    redirect_to parkings_path
  end

  private
  def parking_params
    params.require(:parking).permit(:hour_price, :day_price, :places, :kind, address_attributes: [:city, :street, :zip_code])
  end

  def search_params
    params.permit(:min_hour_price, :max_hour_price, :min_day_price, :max_day_price, :search, :private, :public)
  end
end

app/views/parkings/_form.html.erb
<%= form_for @parking, url: parkings_path, local: true do |form| %>

  <%= form.fields_for :address do |one_address| %>
    <div class='account-input'>
      <%= one_address.label :city, class: 'label' %>
      <%= one_address.text_field :city, class: 'label-parking' %>
      <% if @parking.errors.any? %>
        <div id='error_explanation' class='alert alert-danger' role='alert'>
          <div class:='label'>
            <%= @parking.errors[:'address.city'].first %>
          </div>
        </div>
      <% end %>
    </div>

    <div class='account-input'>
      <%= one_address.label :street, class: 'label' %>
      <%= one_address.text_field :street, class: 'label-parking' %>
      <% if @parking.errors.any? %>
        <div id='error_explanation' class='alert alert-danger' role='alert'>
          <div class:='label'>
            <%= @parking.errors[:'address.street'].first %>
          </div>
        </div>
      <% end %>
    </div>

    <div class='account-input'>
      <%= one_address.label :zip_code, class: 'label' %>
      <%= one_address.text_field :zip_code, class: 'label-parking' %>
      <% if @parking.errors.any? %>
        <div id='error_explanation' class='alert alert-danger' role='alert'>
          <div class:='label'>
            <%= @parking.errors[:'address.zip_code'].join(', ') %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class='account-input'>
    <%= form.label :hour_price, class: 'label' %>
    <%= form.text_field :hour_price, class: 'label-parking' %>
    <% if @parking.errors.any? %>
      <div id='error_explanation' class='alert alert-danger' role='alert'>
        <div class:='label'>
          <%= @parking.errors[:hour_price].join(', ') %>
        </div>
      </div>
    <% end %>
  </div>

  <div class='account-input'>
    <%= form.label :day_price, class: 'label' %>
    <%= form.text_field :day_price, class: 'label-parking' %>
    <% if @parking.errors.any? %>
      <div id='error_explanation' class='alert alert-danger' role='alert'>
        <div class:='label'>
          <%= @parking.errors[:day_price].join(', ') %>
        </div>
      </div>
    <% end %>
  </div>

  <div class='account-input'>
    <%= form.label :places, class: 'label' %>
    <%= form.text_field :places, class: 'label-parking' %>
    <% if @parking.errors.any? %>
      <div id='error_explanation' class='alert alert-danger' role='alert'>
        <div class:=col-xs-3>
          <div class:='label'>
            <%= @parking.errors[:places].join(', ') %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= form.label :kind, class: 'label' %>
  <%= form.select(:kind, Parking.kinds.map {|k, v| [k ,k] }, {}, { :class => 'select'}) %>

  <div class='margins-for-botton'>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/_header.erb
<div class="margins-for-page">
  <div class="media">
    <img class="mr-3" src="https://i.wpimg.pl/730x0/m.gadzetomania.pl/mb2016-35f8e9899c087075c2566f3ec.jpg" alt="Generic placeholder image" height="98" width="146">
    <div class="media-body">
      <h3 class="mt-0">List of all parkings</h3>
      This is a list of all available parkings from our website, to help people find their own place to park their car. All parkings are checked for fulfillment of all law regulations.
    </div>
  </div>
</div>

app/views/parkings/edit.html.erb
<h1>Edit parking</h1>

<%= form_for @parking do |form| %>

  <% if @parking.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@parking.errors.count, "error") %> prohibited
        this parking from being saved:
      </h2>
      <ul>
        <% @parking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :address do |one_address| %>
    <p>
      <%= one_address.label :city %><br>
      <%= one_address.text_field :city %>
    </p>

    <p>
      <%= one_address.label :street %><br>
      <%= one_address.text_field :street %>
    </p>

    <p>
      <%= one_address.label :zip_code %><br>
      <%= one_address.text_field :zip_code %>
    </p>
  <% end %>

  <p>
    <%= form.label :hour_price %><br>
    <%= form.text_field :hour_price %>
  </p>

  <p>
    <%= form.label :day_price %><br>
    <%= form.text_field :day_price %>
  </p>

  <p>
    <%= form.label :places %><br>
    <%= form.text_area :places %>
  </p>

  <p>
    <%= form.label :kind %><br>
    <%= form.text_field :kind %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.erb
<p style="text-align:right;"><%= link_to "Sign in", new_account_registration_path %></p>


<%= render "parkings/header" %>


<div class='search-tags'>
  <%= form_tag(parkings_path, method: 'get', id: 'search-form') do %>

    <%= label_tag 'public_parking', 'Public' %>
    <%= check_box_tag('public', 'Public', true, class: 'checkboxes') %>

    <%= label_tag 'private_parking', 'Private' %>
    <%= check_box_tag('private', 'Private', true, class: 'checkboxes') %>

    <%= text_field_tag('min_hour_price', params[:min_hour_price], placeholder: 'Min hour price', class: 'checkboxes') %>
    <%= text_field_tag('max_hour_price', params[:max_hour_price], placeholder: 'Max hour price', class: 'checkboxes') %>

    <%= text_field_tag('min_day_price', params[:min_day_price], placeholder: 'Min day price', class: 'checkboxes') %>
    <%= text_field_tag('max_day_price', params[:max_day_price], placeholder: 'Max day price', class: 'checkboxes') %>

    <%= text_field_tag('search', params[:search], placeholder: 'Search City', class: 'checkboxes') %>

    <%= submit_tag 'Search', name: nil %>
  <% end %>
</div>


<% if @parkings.blank? %>
  <h4>There are no parkings containing the term <%= params[:search] %>.</h4>
<% end %>

<table class='table' style='width:100%; text-align: center;'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>City</th>
      <th scope='col'>Remaining places</th>
      <th scope='col' scope='col'>Hour price</th>
      <th scope='col'>Day price</th>
      <th scope='col'>Kind</th>
      <th scope='col'>Action</th>
      <th scope='col'>Action</th>
      <th scope='col'>Action</th>
      <th scope='col'></th>
    </tr>
  </thead>
  <% @parkings.each do |parking| %>
    <tr>
      <td><%= parking.address&.city %></td>
      <td><%= parking.places %></td>
      <td><%= parking.hour_price %> zl</td>
      <td><%= parking.day_price %> zl</td>
      <td><%= parking.kind %></td>
      <td><%= link_to 'Details', parking_path(parking.id) %></td>
      <td><%= link_to 'Edit', edit_parking_path(parking) %></td>
      <td><%= link_to 'Delete', parking_path(parking), method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      <td><%= link_to 'Rent a place', new_parking_place_rent_path(parking.id) %></td>
    </tr>
  <% end %>
</table>
<ul>
  <li><%= link_to 'Create new', new_parking_path %></li>
  <li><%= link_to 'List of place rents', place_rents_path %></li>
  <li><%= link_to 'List of cars', cars_path %></li>
</ul>

app/views/parkings/new.html.erb
<div class='account-parking'>
  <h4>Create New Parking</h4>

  <%= render "parkings/form" %>
</div>

app/views/parkings/show.html.erb
<h1>Details to parking</h1>
<pre>
City: <%= @parking.address&.city %>
Street: <%= @parking.address&.street %>
Zip code: <%= @parking.address&.zip_code %>
Owner first name: <%= @parking.owner&.first_name %>
Remaining places: <%= @parking.places %> left
Hour price: <%= @parking.hour_price %> zl
Day price: <%= @parking.day_price %> zl
Kind: <%= @parking.kind %>
Action: <%= link_to "Back", parkings_path %></pre>