config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts, controllers: { registrations: 'accounts/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'parkings#index'

  resources :parkings do
    resources :place_rents, only: [:new, :create]
  end
  resources :place_rents, only: [:index, :show, :destroy]
  resources :cars
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner, class_name: 'Person', optional: true
  has_one :place_rent
  has_one :account
  accepts_nested_attributes_for :owner

  validates :registration_number, :model, :owner, presence: true

  def to_param
    "#{id}-#{model.parameterize}"
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_account!

  def index
    @cars = Car.where(owner_id: current_person.id)
  end

  # def show
  #   @car = Car.where(:model => params[:id]).first
  # end

  def show
    @car = Car.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:error] = "There is no such route"
    redirect_to action: "index"
  end

  def new
    @car = Car.new
    @car.build_owner
  end

  def edit
    @car = Car.find(params[:id])
    @car.build_owner
  end

  def create
    @car = Car.new(car_params)
    @car.owner_id = current_person.id
    if @car.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def update
    @car = Car.find(params[:id])

    if @car.update(car_params)
      redirect_to @car
    else
      render 'edit'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    redirect_to cars_path
  end

  private
  def car_params
    params.require(:car).permit(:registration_number, :model, :owner, cars_attributes: [:first_name, :last_name])
  end
end

app/views/cars/_form.html.erb
<%= form_for @car, url: cars_path, local: true do |form| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car.errors.count, "error") %> prohibited
        this car from being saved:
      </h2>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :registration_number %><br>
    <%= form.text_field :registration_number %>
  </p>

  <p>
    <%= form.label :model %><br>
    <%= form.text_area :model %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', cars_path %>

app/views/cars/edit.html.erb
<h1>Edit car</h1>

<%= form_with(model: @car) do |form| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car.errors.count, "error") %> prohibited
        this car from being saved:
      </h2>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :registration_number %><br>
    <%= form.text_field :registration_number %>
  </p>

  <p>
    <%= form.label :model %><br>
    <%= form.text_area :model %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>List of all cars</h1>
<table style="width:100%; text-align: center;">
  <tr>
    <th>Registration number</th>
    <th>Model</th>
  </tr>
  <% @cars.each do |car| %>
    <tr>
      <td><%= car.registration_number %></td>
      <td><%= car.model %></td>
      <td><%= link_to "Details", car_path(car) %></td>
      <td><%= link_to "Edit", edit_car_path(car) %></td>
      <td><%= link_to "Delete", car_path(car), method: :delete, data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
</table>
<ul>
  <li><%= link_to "Create new", new_car_path %></li>
  <li><%= link_to "List of place rents", place_rents_path %></li>
  <li><%= link_to "List of parkings", parkings_path %></li>
</ul>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "cars/form" %>

app/views/cars/show.html.erb
<h1>Details to car</h1>
<pre>
Owner first name: <%= @car.owner&.first_name %>
Owner last name: <%= @car.owner&.last_name %>
Registration number: <%= @car.registration_number %>
Model: <%= @car.model %>
Action: <%= link_to "Back", cars_path %>
</pre>